version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: enyelberth
      POSTGRES_DB: KAIZEN
      POSTGRES_PASSWORD: 30204334
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: